blank_issues_enabled: false
contact_links:
  - name: Salesforce DX Community
    url: https://success.salesforce.com/issues_index?tag=Salesforce%20DX
    about: Please ask and answer questions here.
  - name: Vulnerability Reporting Policy
    url: https://www.salesforce.com/company/disclosure/
    about: Please report security vulnerabilities here.
